	<section class="scrat" element="section" resizelayout="false">    
		<div type="images" element="content" style="border: none; cursor: default; padding: 0px; position: absolute; top: 41px; left: 44px; width: 295px; background: none;" mode="edit" init="3" resize="false" class="column2 ui-draggable ui-draggable-disabled ui-state-disabled" aria-disabled="true">
	    	<img id="3" src="http://localhost/project/intersweb/templates/default/pic/mobile-website-design.png" width="100%">
	    </div>
	    
	    <div type="title" element="content" style="cursor: default; padding: 0px; left: 392px; top: 32px; border: none; background: none 0% 0% repeat scroll transparent;" mode="edit" class="column2 ui-draggable ui-resizable ui-draggable-disabled ui-state-disabled" init="2" resize="false" aria-disabled="true" font="font6">
	    <h2 class="font5" style="font-size: 26px; color: rgb(255, 128, 0);" font="font6">Produk Baru dari google yaitu google cardboard yang murah</h2>
	    </div>
	    
		<div type="text" element="content" style="border: none; cursor: move; padding: 0px; left: 394px; top: 100px; position: absolute; width: 468px;" mode="edit" class="columnFull ui-resizable ui-draggable" init="4" resize="false" aria-disabled="false">
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This is a great space to write long text about your company and your services. You can use this space to go into a little more detail about your company. Talk about your team and what services you provide. Tell your visitors the story of how you came up with the idea for your business and what makes you different from your competitors. Make your company stand out and show your visitors who you are.This is a great space to write long text about your company and your services. You can use this space to go into a little more detail about your company. Talk about your team and what services you provide. Tell your visitors the story of how you came up with the idea for your business and what makes you different from your competitors. Make your company stand out and show your visitors who you are.This is a great space to write long text about your company and your services. You can use this space to go into a little more detail about your company. Talk about your team and what services you provide. Tell your visitors the story of how you came up with the idea for your business and what makes you different from your competitors. Make your company stand out and show your visitors who you are.
	 	</div>        
    </section>